# -*- coding: utf-8 -*-
import argparse
import json
import os
from collections import OrderedDict
from urllib.parse import urlparse
import re

TRIGGER_EFFECT_PATTERN = re.compile(r"（：[^）]+）")
SOUL_TRIGGER_TEXT = "（：このターン中、このカードをトリガーした攻撃キャラのソウルを+1する）"


def infer_image_name(url):
    if not url:
        return ""
    parsed = urlparse(url)
    filename = os.path.basename(parsed.path).lower()
    return filename


def ensure_list(value):
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, str):
        value = value.strip()
        return [value] if value else []
    return [str(value)]


def get_trigger_urls(card):
    urls = ensure_list(card.get("トリガー_imgs"))
    if not urls and card.get("トリガー_img"):
        urls = [card.get("トリガー_img")]
    return [str(url).strip() for url in urls if str(url).strip()]


def extract_trigger_effect_texts(card):
    effects = []
    for ability in ensure_list(card.get("abilities")):
        text = str(ability).strip()
        if not text:
            continue
        matches = TRIGGER_EFFECT_PATTERN.findall(text)
        for m in matches:
            effects.append(m)
    return effects


def collect_trigger_icon_mappings(cards):
    mappings = OrderedDict()

    for card in cards:
        trigger_urls = get_trigger_urls(card)
        effect_texts = extract_trigger_effect_texts(card)
        image_names = [infer_image_name(url) for url in trigger_urls]
        effect_target_names = {name for name in image_names if name and name != "soul.gif"}

        for url in trigger_urls:
            file_name = infer_image_name(url)
            if not file_name:
                continue

            entry = mappings.setdefault(file_name, {
                "imageFileName": file_name,
                "imageUrl": url,
                "effectTexts": OrderedDict(),
            })

            if not entry["imageUrl"]:
                entry["imageUrl"] = url

            if file_name in effect_target_names:
                for effect_text in effect_texts:
                    entry["effectTexts"][effect_text] = None

    # soul trigger special handling
    soul_entry = mappings.get("soul.gif")
    if soul_entry:
        soul_entry["effectTexts"][SOUL_TRIGGER_TEXT] = None

    return [
        {
            "imageFileName": entry["imageFileName"],
            "imageUrl": entry["imageUrl"],
            "effectTexts": list(entry["effectTexts"].keys()),
        }
        for entry in mappings.values()
    ]


def escape_csharp_string(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate_csharp_file_content(mappings, namespace, class_name):
    mapping_entries = []
    for mapping in mappings:
        effect_text_entries = ", ".join(
            f"\"{escape_csharp_string(text)}\"" for text in mapping["effectTexts"]
        )
        mapping_entries.append(
            "        new TriggerIconMapping\n"
            "        {\n"
            f"            ImageFileName = \"{escape_csharp_string(mapping['imageFileName'])}\",\n"
            f"            ImageUrl = \"{escape_csharp_string(mapping['imageUrl'])}\",\n"
            f"            EffectTexts = new string[] {{ {effect_text_entries} }}\n"
            "        }"
        )

    csharp_mappings = ",\n".join(mapping_entries)

    return f"""// This file is auto-generated by python/tools/generate_trigger_icon_data.py.
// Generated from raw trigger icon URLs and trigger-related ability text examples.
namespace {namespace}
{{
    public struct TriggerIconMapping
    {{
        public string ImageFileName;
        public string ImageUrl;
        public string[] EffectTexts;
    }}

    public static class {class_name}
    {{
        public static readonly TriggerIconMapping[] AllTriggerIcons = new TriggerIconMapping[]
        {{
{csharp_mappings}
        }};
    }}
}}
"""


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, "..", ".."))

    default_input = os.path.join(script_dir, "weiss_schwarz_cards.json")
    default_output = os.path.join(project_root, "Assets", "Scripts", "WeissSchwarz", "Data", "Generated", "TriggerIconData.cs")

    parser = argparse.ArgumentParser(description="Generate a C# trigger icon mapping file from raw Weiss Schwarz scrape data.")
    parser.add_argument("--input", type=str, default=default_input, help="Path to the input raw JSON file.")
    parser.add_argument("--output", type=str, default=default_output, help="Path to the output C# file.")
    args = parser.parse_args()

    try:
        with open(args.input, "r", encoding="utf-8") as f:
            cards = json.load(f)
    except FileNotFoundError:
        print(f"Error: Input file not found at {args.input}.")
        return
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from {args.input}.")
        return

    mappings = collect_trigger_icon_mappings(cards)
    mappings.sort(key=lambda item: item["imageFileName"])

    output_dir = os.path.dirname(args.output)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    content = generate_csharp_file_content(mappings, "TCG.Weiss.Data.Generated", "TriggerIconData")
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Successfully generated trigger icon C# mapping at: {args.output}")
    print(f"Trigger icon count: {len(mappings)}")


if __name__ == "__main__":
    main()
