# -*- coding: utf-8 -*-
import json
import os
import argparse
import re
from collections import OrderedDict

def get_unique_work_ids_from_json(card_data):
    """
    カードデータのリストからユニークな作品IDを抽出します。
    """
    work_ids = set()
    for card in card_data:
        card_no = card.get("cardCode") or card.get("card_no")
        if card_no and "/" in card_no:
            work_id = card_no.split("/")[0]
            work_ids.add(work_id)
    return sorted(list(work_ids))

def parse_existing_csharp_file(filepath):
    """
    既存のC#ファイルからIDと名前のマッピングを解析して辞書として返します。
    """
    mappings = OrderedDict()
    if not os.path.exists(filepath):
        return mappings

    # 正規表現で Id = "...", Name = "..." の部分を抽出
    pattern = re.compile(r'new\s+WorkIdMapping\s*{\s*Id\s*=\s*"(?P<id>[^"]+)"\s*,\s*Name\s*=\s*"(?P<name>[^"]*)"\s*}')
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            for match in pattern.finditer(content):
                mappings[match.group('id')] = match.group('name')
    except Exception as e:
        print(f"Warning: Could not parse existing C# file. A new file will be created. Error: {e}")

    return mappings

def generate_csharp_file_content(mappings, namespace, class_name):
    """
    作品IDと名前のマッピング辞書からC#の静的クラスファイルのコンテンツを生成します。
    """
    
    mapping_entries = []
    for work_id, name in mappings.items():
        # C#の文字列リテラル内でダブルクォートをエスケープ
        escaped_name = name.replace('"', '\"')
        mapping_entries.append(f'        new WorkIdMapping {{ Id = "{work_id}", Name = "{escaped_name}" }}')
    
    csharp_mappings = ',\n'.join(mapping_entries)

    content = f"""// This file is auto-generated by python/tools/generate_work_ids.py.
// Manually add user-friendly names for new entries. Do not delete existing entries.
namespace {namespace}
{{
    public struct WorkIdMapping
    {{
        public string Id;
        public string Name;
    }}

    public static class {class_name}
    {{
        public static readonly WorkIdMapping[] AllWorkIds = new WorkIdMapping[]
        {{
{csharp_mappings}
        }};
    }}
}}
"""
    return content

def main():
    """
    メイン処理。
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, '..', '..'))
    
    default_input = os.path.join(project_root, 'Assets', 'StreamingAssets', 'WeissSchwarz', 'cards.json')
    default_output = os.path.join(project_root, 'Assets', 'Scripts', 'WeissSchwarz', 'Data', 'Generated', 'WorkIdData.cs')

    parser = argparse.ArgumentParser(description="Generate/Update a C# file with unique work IDs and user-friendly names.")
    parser.add_argument("--input", type=str, default=default_input, help="Path to the input JSON file.")
    parser.add_argument("--output", type=str, default=default_output, help="Path to the output C# file.")
    args = parser.parse_args()

    # 1. 既存のC#ファイルから手動設定を読み込む
    print(f"Checking for existing file at {args.output}...")
    existing_mappings = parse_existing_csharp_file(args.output)
    if existing_mappings:
        print(f"Found and parsed {len(existing_mappings)} existing entries.")

    # 2. JSONファイルから最新の作品IDリストを取得
    try:
        with open(args.input, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Error: Input file not found at {args.input}. Please check the path.")
        # 入力JSONがない場合は、既存のC#ファイルをそのままにして終了
        if os.path.exists(args.output):
            print("Keeping the existing C# file.")
            return
        # C#ファイルもなければ何もできない
        print("No source JSON and no existing C# file. Exiting.")
        return
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from {args.input}")
        return

    unique_ids_from_json = get_unique_work_ids_from_json(data)
    print(f"Found {len(unique_ids_from_json)} unique work IDs in the source JSON.")

    # 3. 既存のリストとマージ
    final_mappings = existing_mappings.copy()
    new_ids_count = 0
    for work_id in unique_ids_from_json:
        if work_id not in final_mappings:
            final_mappings[work_id] = ""  # 新しいIDには空の名前を設定
            new_ids_count += 1
    
    if new_ids_count > 0:
        print(f"Added {new_ids_count} new work IDs.")
    else:
        print("No new work IDs to add.")

    # 4. 新しいC#ファイルを生成
    output_dir = os.path.dirname(args.output)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        print(f"Created directory: {output_dir}")

    csharp_content = generate_csharp_file_content(final_mappings, "TCG.Weiss.Data.Generated", "WorkIdData")
    
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(csharp_content)
    
    print(f"Successfully generated/updated C# file at: {args.output}")

if __name__ == "__main__":
    main()
